name: Test Chains on Microshift

permissions:
  contents: read

'on':
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  tekton-chains-e2e-tests-microshift:
    name: Run E2E Tests on Microshift
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    env:
      SHELL: /bin/bash
      GOPATH: ${{ github.workspace }}
      KO_DOCKER_REPO: ko.local
      DOCKER_HOST: tcp://localhost:24816

    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      with:
        path: ${{ github.workspace }}/src/github.com/tektoncd/chains

    - uses: imjasonh/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d  # v0.9

    - name: Set up Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5  # v6.2.0
      with:
        cache-dependency-path: "${{ github.workspace }}/src/github.com/tektoncd/chains/go.sum"
        go-version-file: "${{ github.workspace }}/src/github.com/tektoncd/chains/go.mod"

    - name: setup microshift
      run: |
          curl -L -o minc  https://github.com/minc-org/minc/releases/latest/download/minc_linux_amd64
          chmod +x minc
          ./minc create --log-level debug

    - name: Install Tekton Chains and Run e2e tests
      working-directory: ${{ github.workspace }}/src/github.com/tektoncd/chains

      run: |
          echo -e "\n************************ Install openshift client ************************\n"
          wget https://github.com/okd-project/okd/releases/download/4.19.0-okd-scos.6/openshift-client-linux-amd64-rhel9-4.19.0-okd-scos.6.tar.gz
          tar -xzvf openshift-client-linux-amd64-rhel9-4.19.0-okd-scos.6.tar.gz
          export PATH=${PATH}:${PWD}

          echo -e "\n************************ Setup Podman ************************\n"
          sudo podman system service --time=0 tcp://localhost:24816 &
          sleep 7
          echo -e "\ntest the podman tcp connection\n"
          curl http://localhost:24816/_ping

          echo -e "\n************************ Starting e2e ************************\n"
          oc adm policy add-scc-to-user anyuid -z tekton-pipelines-controller
          oc adm policy add-scc-to-user anyuid -z tekton-pipelines-webhook

          export KUBECONFIG=$HOME/.kube/config

          source ${{ github.workspace }}/src/github.com/tektoncd/chains/test/microshift_test.sh